name: Deploy Utility to Quay

#on:

  # schedule:
  #   - cron: '0 2 * * *' # run at 2 AM UTC
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Login Quay.io
      uses: docker/login-action@v1.14.1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Rake Variables
      run: |
        set -x ; \
        echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
        echo;
        
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./workshop/files/
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
         quay.io/redhat-ai-services/rhai-toolbox:latest

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"